export const NOT_FOUND_ERROR = 'Invalid Api call: Api not found'
export const PRODUCT_DATA_FETCH_ERROR = 'Could not fetch Products data'
export const CATEGORY_DATA_FETCH_ERROR = 'Could not fetch Category data'
export const PRODUCT_NOT_FOUND = 'Product Id Missing'
export const PRODUCT_ID_INVALID = 'Invalid Product Id Format'
export const PRODUCT_ID_MISSING = 'Product Not Found'
export const CATEGORY_NOT_FOUND = 'Category Id Missing'
export const CATEGORY_ID_INVALID = 'Invalid Category Id Format'
export const CATEGORY_ID_MISSING = 'Category Not Found'
export const USER_NOT_FOUND = 'User Id Missing'
export const USER_ID_INVALID = 'Invalid User Id Format'
export const USER_ID_MISSING = 'User Not Found'
export const UNABLE_TO_FETCH_PRODUCT_RESPONSE = 'Unable to fetch product Response'
export const UNABLE_TO_FETCH_PRODUCTS_RESPONSE = 'Unable to fetch products Response'
export const USER_DELETED_SUCCESSFULLY = 'User Deleted Successfully'
export const PRODUCT_DELETED_SUCCESSFULLY = 'Product Deleted Successfully'
export const CATEGORY_DELETED_SUCCESSFULLY = 'Category Deleted Successfully'
export const ERROR_DELETING_USER = 'Error in deleting User'
export const ERROR_DELETING_PRODUCT = 'Error in deleting Product'
export const ERROR_DELETING_CATEGORY = 'Error in deleting Category'
export const USER_ADDED_SUCCESSFULLY = 'User Deleted Successfully'
export const PRODUCT_ADDED_SUCCESSFULLY = 'Product Deleted Successfully'
export const CATEGORY_ADDED_SUCCESSFULLY = 'Category Deleted Successfully'
export const ERROR_ADDING_USER = 'Error in adding User'
export const ERROR_ADDING_PRODUCT = 'Error in adding User Product'
export const ERROR_ADDING_CATEGORY = 'Error in adding User Category'
export const ERROR_UPDATING_PRODUCT = 'Error in updating Product'
export const ERROR_UPDATING_CATEGORY = 'Error in updating Category'
export const ERROR_UPDATING_USER = 'Error in updating User'
export const PRODUCT_UPDATED_SUCCESSFULLY = 'Product Updated Successfully'
export const CATEGORY_UPDATED_SUCCESSFULLY = 'Category Updated Successfully'
export const USER_UPDATED_SUCCESSFULLY = 'User Updated Successfully'
export const QRCODE_GENERATION_ERROR = 'QR code generation error'
export const PRODUCT_HISTORY_TYPES = {
  CREATED: 'Product created',
  QUANTITY_UPDATED: 'Quantity Updated',
}
